### ISSUE TITLE
Limit the number of results returned

### ISSUE THREAD

**Issue by jennafu** [spinlud/py-linkedin-jobs-scraper#15]
Is there a way to set the limit, to the number of jobs found? 

For instance, in the screenshot below, I have set the limit to 50, and in the log it 'Found 18 jobs', so it ended up returning 18 entries that are related to the query and 32 additional ones that are not as relevant to the query.

![Screenshot 2021-05-25 165117](https://user-images.githubusercontent.com/63271028/119566721-75cd1880-bd79-11eb-8532-df090522e25a.png)

**Comment by spinlud** [comment]
Hi there,
that number is not the total number of jobs existing for that query (it could be much higher) but just the number of jobs currently found in the page  in that moment (jobs are lazy loading), so you should not base any action on that number. 
I agree is kind of misleading :-)

**Comment by jennafu** [comment]
Ahh thanks for the clarification! :)
