### ISSUE TITLE
Using 'experience' filter returns no results found.

### ISSUE THREAD

**Issue by AnkitaTW** [spinlud/py-linkedin-jobs-scraper#17]
I have tried applying and using the experience filter in the query. But the query returns no results found with any value for experience filter.

When I remove the filter for 'experience' I get the job postings. Can you please help me resolve this?

```queries = [
    Query(
        query='Data Engineer',
        options=QueryOptions(
            locations=['India'],
            optimize=False,
            limit=25,
            filters=QueryFilters(
                company_jobs_url='https://www.linkedin.com/jobs/search/?f_C=1441%2C17876832%2C791962%2C2374003%2C18950635%2C16140%2C10440912',  # Filter by companies
                relevance=RelevanceFilters.RECENT,
                time=TimeFilters.MONTH,
                type=[TypeFilters.FULL_TIME],
                experience=[ExperienceLevelFilters.MID_SENIOR,ExperienceLevelFilters.ENTRY_LEVEL,ExperienceLevelFilters.ASSOCIATE,ExperienceLevelFilters.DIRECTOR],
            )
        )
    )
]
```

**Comment by spinlud** [comment]
Hi there, it seems correct to have zero results with your query filters:

![image](https://user-images.githubusercontent.com/12783208/124089908-a4af6c00-da54-11eb-8169-548c7cebb81c.png)

As you can see, there are no jobs available if you specify an experience filter.
