### ISSUE TITLE
LinkedIn changed selector

### ISSUE THREAD

**Issue by src73** [spinlud/py-linkedin-jobs-scraper#22]
Hi, I was getting `no jobs found` for common authenticated searches like "MBA". It looks like LinkedIn changed the name of the container that the scraper uses to validate that the page has loaded. The old and new selector seem to be: 

```
#old search results container
'.jobs-search-two-pane__container'

#new search results container
'.scaffold-layout__list-container'
```

I'm not able to make a PR, but I was able to successfully scrape after I changed line 23 of `authenticated-strategy.py` to 
```
container = '.scaffold-layout__list-container'
```
It looks like the other important selectors are still working, it's just the initial validation one that changed. 

Thanks for making this very useful tool 😄

**Comment by spinlud** [comment]
Thank you sir!
I've just updated the container selector, let me know if it works!
