### ISSUE TITLE
containerization with docker

### ISSUE THREAD

**Issue by JoSuru** [spinlud/py-linkedin-jobs-scraper#23]
can I dockerize and deploy it on a server I say this for the fact that it uses chrome

**Comment by spinlud** [comment]
Yes you can. I am using this docker image to run tests for example:

* [hub.docker.com/r/spinlud/python3-selenium-chrome](https://hub.docker.com/r/spinlud/python3-selenium-chrome)
* [github.com/spinlud/python3-selenium-chrome](https://github.com/spinlud/python3-selenium-chrome)

**Comment by JoSuru** [comment]
yes but I but what     chrome_executable_path=None
