### ISSUE TITLE
Help with getting Authenticated Session

### ISSUE THREAD

**Issue by amoiza1** [spinlud/py-linkedin-jobs-scraper#26]
Can anyone please help me, I have spent 3 days on this and getting to the point of exhaustion.

I have not been able to run authenticated session. I retrieved li_at cookie from chrome but cannot set the li_at environment variable of chrome. I have tried using set li_at = 'xxx' in command prompt but it doesn't work, I even added chrome in my path. Do I need to assign cookie in the code too, I see there is a chrome_cdp class but I don't know how to use it?

Would really appreciate if someone can please help on this? I have just not been able to run authenticated session.

**Comment by amoiza1** [comment]
I am sorry I figured it out. I was using a different environment in Anaconda that's why it couldn't detect the variables in main os environment

**Comment by spinlud** [comment]
https://github.com/spinlud/linkedin-jobs-scraper/issues/35#issuecomment-1109628093
