### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by aymagee92** [spinlud/py-linkedin-jobs-scraper#29]
Thank you for putting this together. I've used it on and off for the last year and it's great.

I am trying to do an authenticated session. I've successfully pulled the cookie value, but it still runs it as an anonymous session. What is meant by the "python your_app.py" that is listed after the cookie value?

**Comment by spinlud** [comment]
If you are launching your script from terminal like:

```sh
python myscript.py
```

you can set environment variables in one line like:

```sh
LI_AT_COOKIE="ABCD1234" python myscript.py
```

**Comment by aymagee92** [comment]
I'm running it from Visual Studio Code. Typing this at the end throws an error. Running it with LI_AT_COOKIE="ABCD1234" runs it as an anonymous strategy.

**Comment by aymagee92** [comment]
If I copy and paste the "ABCD1234" to the LI_AT_COOKIE= variable and run it from Visual Studio Code, should that run it as an authenticated session? When I do that, it's currently still running as anonymous.

**Comment by aymagee92** [comment]
I was able to get it to an authentication session by placing the LI_AT_COOKIE and the value in the operating system's environmental variables. You will also have to close our and re-open your code editor for it to work.

https://imgur.com/JbEFzcG

**Comment by spinlud** [comment]
Yes you can also define env variables in that way on windows 👍

**Comment by aymagee92** [comment]
What?
