### ISSUE TITLE
Not working currently

### ISSUE THREAD

**Issue by yusiyoh** [spinlud/py-linkedin-jobs-scraper#30]
Thank you for this scraper. It was working before but now, I cannot make it work with LI_AT_COOKIE. It gives the following errors:

![image](https://user-images.githubusercontent.com/6302128/167929039-6ba46cda-75f0-422f-8f75-788640e98349.png)

**Comment by spinlud** [comment]
What version of chrome/chromedriver are you using?

**Comment by yusiyoh** [comment]
The latest stable version: 101.0.4951.41
Before, i was using different version but it stopped working thus I downloaded this version, still not working with authentication.

**Comment by spinlud** [comment]
Weird, I am on `101.0.4951.41` too and it is working on my side. Do you get this when you just launch the application?

**Comment by yusiyoh** [comment]
By the way, the example code does not work for me either. And I tried to log off log in to get a different LI_AT cookie, but the results is same even the cookie is different.

**Comment by yusiyoh** [comment]
I created a new acc, it worked this time. There is an issue with my original account it seems.
