### ISSUE TITLE
[No jobs found, skip] But there IS jobs, for some cookie

### ISSUE THREAD

**Issue by VincentChanLivAway** [spinlud/py-linkedin-jobs-scraper#36]
I used one li_at cookie and got this error for whatever URL it's trying to fetch.

eg. https://www.linkedin.com/jobs/search?keywords=mandarin&location=Canada&sortBy=DD&f_TPR=r604800&f_E=1&start=0

I can open this URL from website, lots of jobs, but when I run the scraper it gave me this [No jobs found, skip] warning. 

`INFO:li:scraper:('Using strategy AuthenticatedStrategy',)
EXP level: 0
Start page 1.0
INFO:li:scraper:('Starting new query', "Query(query=mandarin options=QueryOptions(limit=25 locations=['Canada'] filters=QueryFilters(relevance=RelevanceFilters.RECENT time=TimeFilters.WEEK experience=[<ExperienceLevelFilters.INTERNSHIP: '1'>] start=0) optimize=False apply_link=True))")
INFO:li:scraper:('Chrome debugger url', 'http://localhost:50217')
INFO:li:scraper:('[mandarin][Canada]', 'Setting authentication cookie')
INFO:li:scraper:('[mandarin][Canada]', 'Opening https://www.linkedin.com/jobs/search?keywords=mandarin&location=Canada&sortBy=DD&f_TPR=r604800&f_E=1&start=0')
WARNING:li:scraper:('[mandarin][Canada]', 'No jobs found, skip')
[ON_END]`

Also, I used another linked In account to obtain a li_at cookie, it works. No this warning.

**Comment by igncampa** [comment]
see #38

**Comment by spinlud** [comment]
Hi, should be fixed in the latest version
