### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by PARODBE** [spinlud/py-linkedin-jobs-scraper#44]
Hi,

Sorry for so easy question, in windows how is it possible to authenticate in a jupyter notebook using this LI_AT_COOKIE=<your li_at cookie value here> python your_app.py?

Could you help me please?

Thanks
Pablo

**Comment by PARODBE** [comment]
Hi again,

I could authenticate in windows usin ---->  setx LI_AT_COOKIE "value of LI_AT"  

After of that I open a jupyter notebook but I obtain the error: InvalidCookieException

Could you help me please????

**Comment by PARODBE** [comment]
Solved

**Comment by dionator** [comment]
@PARODBE, care to share how you solved your issue?
Running into the same problem on a MacBook. Keep getting InvalidCookieException after setting my environment variable with the correct cookie setting.

**Comment by PARODBE** [comment]
Hi @dionator! I solved this in the same Notebook. Puto os.environ['LI_AT_COOKIE']="......" Here put your Li_at. And after in another cell do a pronto(os.environ['LI_AT_COOKIE'] for load the enviaron and after you can run your query.

Tell me know If It works for you, please.

Pd. The query for company doesn't work for me, the rest yes.

Cheers
Pablo
