### ISSUE TITLE
Possible to add additional filters?

### ISSUE THREAD

**Issue by leonpawelzik** [spinlud/py-linkedin-jobs-scraper#49]
Is it possible to add additional filters? Such as Industry or Job Function?
If I search for a term (i.e. Product Management in Germany) I'm capped by the 40 pages, which equals to 1000 results. Afterwards I get prompted with "no matching job results". Therefore it would be great if I could streamline to certain job functions, so that only Jobs with "product management" in the title are included.
<img width="531" alt="Screenshot 2022-11-09 at 12 29 27" src="https://user-images.githubusercontent.com/78536240/200818885-2a93645c-2577-4426-ad26-c8b75c93789d.png">
<img width="503" alt="Screenshot 2022-11-09 at 12 29 42" src="https://user-images.githubusercontent.com/78536240/200818931-e4a6da0c-0246-4c55-8ad5-eeb31e860e8c.png">

**Comment by nzwade** [comment]
For industry filter support see PR #63
