### ISSUE TITLE
Company name and apply link missing

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/py-linkedin-jobs-scraper#51]
The scraper is working, however it's not returning company name nor apply link. The strings are empty.

**Comment by tharindukulasinghe** [comment]
same issue

**Comment by tharindukulasinghe** [comment]
@calvinomiguel did you got any workaround?

**Comment by calvinomiguel** [comment]
> @calvinomiguel did you got any workaround?
> 
> 

Unfortunately not. I tried using different HTML selectors, yet I am still getting empty strings. I am surely missing something in the logic.

**Comment by spinlud** [comment]
Hi, company name seems to work fine here. For apply link, please try latest version (latest chrome drivers tested is `108.0.5359.71`)

**Comment by calvinomiguel** [comment]
> Hi, company name seems to work fine here. For apply link, please try latest version (latest chrome drivers tested is `108.0.5359.71`)

Hi there. Thanks for the feedback. Unfortunately it's not working. I have checked I already have the latest version of chrome and as well of the chrome driver. On both, node and python scraper, I apply link and company name are missing. However everything else is working. Could it also be that I was blocked?

**Comment by spinlud** [comment]
That's weird. Are we talking about authenticated sessios right? Because anonymous session is no longer mantained.

This is my test:

```python
import logging
from linkedin_jobs_scraper import LinkedinScraper
from linkedin_jobs_scraper.events import Events, EventData, EventMetrics
from linkedin_jobs_scraper.query import Query, QueryOptions, QueryFilters

logging.basicConfig(level=logging.INFO)


def on_data(data: EventData):
    print(f'Company = "{data.company}" | Apply Link = "{data.apply_link}"')


scraper = LinkedinScraper(
    chrome_executable_path=None,
    chrome_options=None,
    headless=True,
    max_workers=1,
    slow_mo=0.5,
    page_load_timeout=30
)

scraper.on(Events.DATA, on_data)

scraper.run([
    Query(
        query='Product Manager',
        options=QueryOptions(
            locations=['Germany'],
            apply_link=True,
            skip_promoted_jobs=False,
            limit=10,
        )
    ),
])
```

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/12783208/210354394-53884afd-7d79-4fb6-be71-a3a1175c08d4.png">

**Comment by luigikitten** [comment]
Same issue here - let me know if I can provide some useful information to troubleshoot it....

I am on Windows, python3.10.9, linkedin-jobs-scraper==2.0.4 , authenticated session, account language=English, chrome 108.0.5359.125 - no difference between headless=True and False

**Comment by calvinomiguel** [comment]
@luigikitten @spinlud I think LinkedIn put some restrictions on me or something like that. I tried scrapping with another account's LI_AT cookie. A friend gave me his cookie, and when I used it, it worked this time. It's not that the scraper doesn't work when I use it, it works, it's just that some data, like the company's name, is missing.

**Comment by luigikitten** [comment]
Checking the linkedin page, it seems that in my case the company title is
not inside a <a> but inside a <div>:

<div id="ember425" class="artdeco-entity-lockup__subtitle ember-view">
            <div class="job-card-container__company-name">
              FERCHAU
            </div>
</div>

while on line 31 of
https://github.com/spinlud/py-linkedin-jobs-scraper/blob/f8cdac2269d840efa8e7ea31c5210469c7a031c3/linkedin_jobs_scraper/strategies/authenticated_strategy.py
the selector requires a <a>

is it possible?
Luigi

**Comment by calvinomiguel** [comment]
@luigikitten I am not sure if it because of that. I am still tipping on restriction. I tried to mess with the selectors too, as I saw the same thing as you, however when I let the scraper run, the result is the same. But when I use someone else's LI_AT_COOKIE it works, just mine doesn't  work. Maybe one curious occurrence: When I first tried another account's cookie, I switched back zo my account's cookie. When I did that, that scraping round worked again with my own cookie. When I tried to go one more round, the issue started again. So right now I am scrapping with a friends LI_AT_COOKIE.

**Comment by spinlud** [comment]
I have just tested the same above script on Windows 10 and python 3.9, it worked the same as on Mac:

![image](https://user-images.githubusercontent.com/12783208/212552450-012e6164-add3-4bfd-a08b-ef47f82f0028.png)

@calvinomiguel you and your friend are scraping in the same country?

**Comment by calvinomiguel** [comment]
Yep, he is from the same city as I and what's essential is that everything is happening on my MacBook. I even tried my second MacBook and the result was the same. It worked with his cookie on my computer but it didn't work with my own LinkedIn cookie.

**Comment by spinlud** [comment]
Interesting. Maybe for some reason a different UI is loaded for your account, which means different CSS selectors. Have you checked if this is the case, e.g. for the company name? The selector currently used is `a.job-card-container__company-name` and we extract `innterText` from this element

**Comment by luigikitten** [comment]
In my case, being authenticated or not changes the behaviour (see also my
comment above):

output of a test script, same Query:

-- ANONYMOUS
COMPANY= Siemens
COMPANY= Siemens
COMPANY= Siemens
COMPANY= Charlton Morris
COMPANY= Cisco
COMPANY= Airswift

-- AUTHENTICATED
COMPANY=
COMPANY=
COMPANY=
COMPANY=
COMPANY=

**Comment by luigikitten** [comment]
I have probably found the issue: in my case, in the authenticated case the company name is NOT inside a <a> ...
The patch below fixes my specific case (but breaks a number of things..)

```
--- a/linkedin_jobs_scraper/strategies/authenticated_strategy.py
+++ b/linkedin_jobs_scraper/strategies/authenticated_strategy.py
@@ -27,7 +27,7 @@ class Selectors(NamedTuple):
     link = 'a.job-card-container__link'
     applyBtn = 'button.jobs-apply-button[role="link"]'
     title = '.artdeco-entity-lockup__title'
-    company = '.artdeco-entity-lockup__subtitle'
+    company = '.job-card-container__company-name'
     company_link = 'a.job-card-container__company-name'
     place = '.artdeco-entity-lockup__caption'
     date = 'time'
@@ -434,7 +434,7 @@ class AuthenticatedStrategy(Strategy):
                             Selectors.jobs,
                             Selectors.link,
                             Selectors.title,
-                            Selectors.company_link,
+                            Selectors.company,
                             Selectors.place,
                             Selectors.date)
```

**Comment by spinlud** [comment]
I have changed company selector to `.job-card-container__company-name`. Since you have facing different UI, probably you won't have the `company_link` field properly set but at least `company` should be.

**Comment by mahlettaye** [comment]
I have checked all the options provided here changing the driver version to 108.0.5359.71 but not working

**Comment by spinlud** [comment]
> I have checked all the options provided here changing the driver version to 108.0.5359.71 but not working

Can you please retry with latest version and chrome/driver 118?
