### ISSUE TITLE
Location is always set to worldwide even after changing parameters

### ISSUE THREAD

**Issue by ManalIrfan** [spinlud/py-linkedin-jobs-scraper#58]
![image](https://github.com/spinlud/py-linkedin-jobs-scraper/assets/45544556/0f00a0c3-6d23-41b1-9746-c8bd5d6e1ca0)
![image](https://github.com/spinlud/py-linkedin-jobs-scraper/assets/45544556/2dad295c-910e-470c-ac66-ee480af3002b)

**Comment by spinlud** [comment]
Hi, anonymous mode is no longer mantained. Please use [authenticated session](https://github.com/spinlud/py-linkedin-jobs-scraper#anonymous-vs-authenticated-session)
