### ISSUE TITLE
"company" field is empty.

### ISSUE THREAD

**Issue by nibomed** [spinlud/py-linkedin-jobs-scraper#61]
Yesterday everything was ok, but today "data" always have an empty "company" field inside "Events.DATA" callback.
Maybe something changed in LinkedIn DOM. I am not an expert in this area, but I will try to investigate it.
Please check if this is reproducible or if it's my local issue.

**Comment by nibomed** [comment]
Please review my attempt to fix this:
https://github.com/spinlud/py-linkedin-jobs-scraper/pull/62

**Comment by spinlud** [comment]
Thank you! 🍻

Merged 🚀
