### ISSUE TITLE
add job filter keywords to avoid 429 error

### ISSUE THREAD

**Issue by je888** [spinlud/py-linkedin-jobs-scraper#65]
Problem:
for anonamous strategy, currently we have to slow down the by setting a very long interval because we are looking into every job in details, clicking into it to get the job place, date, and descriptions.

Potential solution:
add a regex filter on the API so that we don't have to click into every job and only click into jobs that is really interesting to us.

**Comment by spinlud** [comment]
Hi, anonymous strategy is no longer mantained
