### ISSUE TITLE
Explain how Dockerfile Chromedriver works

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/py-linkedin-jobs-scraper#77]
I am trying to understand how the Dockerfile chromedrive can be used. You just put the link in there, but how exactly do i integrate in the code? A short tutorial or detailled explanation would be cool. [Chromedriver](https://chromedriver.chromium.org/): latest version tested is 119.0.6045.105 ([Dockerfile](https://github.com/spinlud/python3-selenium-chrome/blob/master/Dockerfile))

**Comment by spinlud** [comment]
You don't need to integrate that in your code. It is just for reference to show on what environment the code is tested. 
For learning how Docker works I recommend the Docker official website or youtube, there are plenty of tutorials.
