### ISSUE TITLE
Token expires between 3~15 minutes upon start of scrapping

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/py-linkedin-jobs-scraper#80]
I can't really scrape many jobs anymore. The scraper keeps crashing after a few minutes because LinkedIn deletes the `LI_AT` token and forces me to log in again. Are there any best practices to prevent this? By the way, it doesn't matter how fast or slow I set the `slow_mo` value, the `LI_AT` token is deleted by LinkedIn within 3 to 15 minutes after the scraping starts.

**Comment by spinlud** [comment]
See https://github.com/spinlud/py-linkedin-jobs-scraper/issues/76
