### ISSUE TITLE
Ending without scrapping anything

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/py-linkedin-jobs-scraper#93]
Suddenly I can't scrap anymore. Not sure if it's because of the update but I this what's happening when I try to scrap:
<img width="2183" alt="grafik" src="https://github.com/user-attachments/assets/1bf48dab-fb8b-4bc7-9297-60fe3658a1bc">

The chromedriver's version is 131.0.6778.85  and my chrome browser's version is 131.0.6778.86

**Comment by calvinomiguel** [comment]
@DenDeline is this the results list?
<img width="2416" alt="grafik" src="https://github.com/user-attachments/assets/c8b087ca-0402-47ce-b0ed-0e59a554811f">

**Comment by booxter** [comment]
FYI I've found this one-liner fix in one of the forks that seems to resolve the issue: https://github.com/dorutowa/py-linkedin-jobs-scraper/commit/c645bd820b0d3b924ef52162da03272da61297e2

**Comment by calvinomiguel** [comment]
@booxter I did this
<img width="527" alt="grafik" src="https://github.com/user-attachments/assets/6bbd7d77-cab6-430b-a05b-f8167f15391c">
